// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9ebd2254-c614-4a67-a37e-0dacae04d038";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedSwitchChange();
void onTemperatureCChange();
void onTemperatureFChange();

CloudLight lED1;
CloudSwitch led_switch;
CloudTemperatureSensor temperatureC;
CloudTemperatureSensor temperatureF;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lED1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led_switch, READWRITE, ON_CHANGE, onLedSwitchChange);
  ArduinoCloud.addProperty(temperatureC, READWRITE, ON_CHANGE, onTemperatureCChange);
  ArduinoCloud.addProperty(temperatureF, READWRITE, ON_CHANGE, onTemperatureFChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
